[systemd]
gtk_theme = Adwaita
icon_theme = Adwaita
font_name = Sans 12
overlay_scrolling = false
color_scheme = prefer-dark

[component:wf-panel]
command = wf-panel
enabled = true
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false
session_service = true
# wf-panel uses dbus freedesktop.login1, which on some setup requires extra permissions

[component:wf-dock]
command = wf-dock
enabled = false
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:wf-background]
command = wf-background
enabled = true
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:waybar]
command = waybar -c ~/.config/waybar/wayfire.json -s ~/.config/waybar/style.css
enabled = false
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:mako]
command = mako
enabled = false
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:dunst]
command = dunst
enabled = false
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:swaync]
command = swaync
enabled = false
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:wpaperd]
command = wpaperd -d
enabled = false
restart_on_crash = true
restart_on_graceful = false
fork_on_start = true

[component:kanshi]
command = kanshi
enabled = true
restart_on_crash = true
restart_on_graceful = true
fork_on_start = false

[component:swayidle]
command = swayidle
enabled = true
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:blueman-applet]
command = blueman-applet
enabled = true
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:steam]
command = steam -silent
enabled = true
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:keepassxc]
command = keepassxc --minimized
enabled = true
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:wf-osk]
command = wf-osk
enabled = false
restart_on_crash = true
restart_on_graceful = false
fork_on_start = false

[component:zenity-message]
command = zenity --title "Welcome back" --info --text "We've got some jobs lined up for you"
enabled = false
restart_on_crash = false
restart_on_graceful = false
fork_on_start = false
